---
title: "Figure1D"
output: html_document
---


<style>
pre {
  overflow-x: auto;
}
pre code {
  word-wrap: normal;
  white-space: pre;
}
.table{
  width:auto;
  font-size: 10px;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE, results=TRUE, fig.align='center', fig.height=5, fig.width=8)
library(knitr)
```


## Load Data


```{r}
dataset <- read.delim("raw_data/Figure1D.txt", stringsAsFactors = FALSE)

dataset$genotype <-  factor(gsub(" $","",dataset$genotype), levels = c("WT", "PARP1 KO", "ALC1 KO #1", "ALC1 KO #2", "ALC1 KO #3", "ALC1 KO PARP1 KO #1", "ALC1 KO PARP1 KO #2"))
                            
dataset$Experiment <- factor(rep(paste0("exp", 1:(length(dataset$genotype)/length(levels(dataset$genotype)))), each=length(unique(dataset$genotype))))

# genotype+Experiment gives unique ID (UID)
dataset$UID <- factor(paste(dataset$Experiment, dataset$genotype))

# wide format
kable(dataset, row.names = F)

library(reshape2)
# reshape to long format
dataset <- melt(dataset, variable.name = "Treatment", value.name = "Counts")

dataset$genotype <- relevel(dataset$genotype, ref = "WT")
dataset$UID <- relevel(dataset$UID, ref = "exp1 WT")

dataset$Olaparib <- gsub("NT","1",dataset$Treatment)
dataset$Olaparib <- gsub("olaparib_|nM","",dataset$Olaparib)
dataset$Olaparib <- log10(as.integer(dataset$Olaparib))




dataset$Offset <- NA
for(uid in levels(dataset$UID)){
        dataset$Offset[dataset$UID == uid] <- mean(dataset$Counts[dataset$UID == uid])
}

dataset$NormCounts <- dataset$Counts / dataset$Offset



dataset$Offset2 <- NA
for(gidx in levels(dataset$genotype)){
        dataset$Offset2[dataset$genotype == gidx] <- mean(dataset$NormCounts[dataset$genotype == gidx & dataset$Olaparib == 0])
}

dataset$NormCounts2 <- dataset$NormCounts / dataset$Offset2



# long format
kable(dataset, row.names = F)
```


## Plot Data


```{r, fig.height=5, fig.width=18}
library(ggplot2)

# raw data
ggplot(dataset, aes(x=Olaparib, y=Counts)) + 
        theme_bw() +
        theme(panel.grid=element_blank(), text = element_text(size=14)) +
        geom_smooth(method=lm, formula = y ~ poly(x, 2), se=FALSE, colour="#666666") +
        geom_point(aes(colour=Treatment, shape=Experiment), size=2) +        
        facet_grid(. ~ genotype) +
        xlab(label = "Olaparib (log10 nM)") +
        scale_shape_manual(values=15:19) +
        scale_color_manual(values=c("#999999","#0072B2","#CC79A7","#009E73"))
```


```{r, fig.height=4, fig.width=10}
# NormCounts Linear
ggplot(dataset[dataset$genotype %in% levels(dataset$genotype)[c(1,2,6,7)],], aes(x=Olaparib, y=NormCounts)) + 
        theme_bw() +
        theme(panel.grid=element_blank(), text = element_text(size=14)) +
        geom_point(colour="#333333") +
        geom_smooth(method=lm, formula = y ~ x, se=TRUE, colour="#666666") +
        facet_grid(. ~ genotype) +
        xlab(label = "Olaparib (log10 nM)")


# NormCounts Quadratic
ggplot(dataset[dataset$genotype %in% levels(dataset$genotype)[c(1,2,6,7)],], aes(x=Olaparib, y=NormCounts)) + 
        theme_bw() +
        theme(panel.grid=element_blank(), text = element_text(size=14)) +
        geom_point(colour="#333333") +
        geom_smooth(method=lm, formula = y ~ poly(x, 2), se=TRUE, colour="#666666") +
        facet_grid(. ~ genotype) +
        xlab(label = "Olaparib (log10 nM)") 


# NormCounts Cubic
ggplot(dataset[dataset$genotype %in% levels(dataset$genotype)[c(1,2,6,7)],], aes(x=Olaparib, y=NormCounts)) + 
        theme_bw() +
        theme(panel.grid=element_blank(), text = element_text(size=14)) +
        geom_point(colour="#333333") +
        geom_smooth(method=lm, formula = y ~ poly(x, 3), se=TRUE, colour="#666666") +
        facet_grid(. ~ genotype) +
        xlab(label = "Olaparib (log10 nM)") 


# NormCounts2 Linear
ggplot(dataset[dataset$genotype %in% levels(dataset$genotype)[c(1,2,6,7)],], aes(x=Olaparib, y=NormCounts2)) + 
        theme_bw() +
        theme(panel.grid=element_blank(), text = element_text(size=14)) +
        geom_point(colour="#333333") +
        geom_smooth(method=lm, formula = y ~ x, se=TRUE, colour="#666666") +
        facet_grid(. ~ genotype) +
        xlab(label = "Olaparib (log10 nM)")


# NormCounts2 Quadratic
ggplot(dataset[dataset$genotype %in% levels(dataset$genotype)[c(1,2,6,7)],], aes(x=Olaparib, y=NormCounts2)) + 
        theme_bw() +
        theme(panel.grid=element_blank(), text = element_text(size=14)) +
        geom_point(colour="#333333") +
        geom_smooth(method=lm, formula = y ~ poly(x, 2), se=TRUE, colour="#666666") +
        facet_grid(. ~ genotype) +
        xlab(label = "Olaparib (log10 nM)") 


# NormCounts2 Cubic
ggplot(dataset[dataset$genotype %in% levels(dataset$genotype)[c(1,2,6,7)],], aes(x=Olaparib, y=NormCounts2)) + 
        theme_bw() +
        theme(panel.grid=element_blank(), text = element_text(size=14)) +
        geom_point(colour="#333333") +
        geom_smooth(method=lm, formula = y ~ poly(x, 3), se=TRUE, colour="#666666") +
        facet_grid(. ~ genotype) +
        xlab(label = "Olaparib (log10 nM)") 


library(Cairo)

cairo_pdf("Figure1D_v1.pdf", width = 10, height = 4, family = "Arial")

datasubset <- dataset[dataset$genotype %in% levels(dataset$genotype)[c(1,2,3,7)],]
datasubset$genotype <- relevel(datasubset$genotype, ref = "WT")

ggplot(datasubset, aes(x=Olaparib, y=NormCounts2)) + 
        theme_bw() +
        theme(panel.grid.major=element_blank(), panel.grid.minor=element_blank(), 
              axis.line = element_line(colour = "black"), text = element_text(size=14),
              panel.border = element_blank(), panel.background = element_blank()) +
        geom_point(aes(colour = genotype)) +
        geom_smooth(method=lm, formula = y ~ poly(x, 2), se=TRUE, aes(colour = genotype), fill='#DDDDDD', size=0.5) +
        facet_grid(. ~ genotype) +
        xlab(label = "Olaparib (log10 nM)") +
        ylab(label = "Normalized Counts") +
        scale_color_manual(values=c('#000000','#800000','#000080','#808080'))

dev.off()



cairo_pdf("Figure1D_v2.pdf", width = 6, height = 4, family = "Arial")

ggplot(datasubset, aes(x=Olaparib, y=NormCounts2)) + 
        theme_bw() +
        theme(panel.grid.major=element_blank(), panel.grid.minor=element_blank(), 
              axis.line = element_line(colour = "black"), text = element_text(size=14),
              panel.border = element_blank(), panel.background = element_blank()) +
        geom_point(aes(colour = genotype), size=1.75) +
        geom_smooth(method=lm, formula = y ~ poly(x,2), se=TRUE, 
                    aes(group = genotype, colour = genotype), fill='#DDDDDD', size=0.5) +
        #facet_grid(. ~ genotype) +
        xlab(label = "Olaparib (log10 nM)") +
        ylab(label = "Normalized Counts") +
        scale_color_manual(values=c('#000000','#800000','#000080','#808080'))

dev.off()


cairo_pdf("FigureS1D.pdf", width = 6, height = 4, family = "Arial")

datasubset <- dataset[dataset$genotype %in% levels(dataset$genotype)[c(1,2,4,5,6)],]
datasubset$genotype <- relevel(datasubset$genotype, ref = "WT")

ggplot(datasubset, aes(x=Olaparib, y=NormCounts2)) + 
        theme_bw() +
        theme(panel.grid.major=element_blank(), panel.grid.minor=element_blank(), 
              axis.line = element_line(colour = "black"), text = element_text(size=14),
              panel.border = element_blank(), panel.background = element_blank()) +
        geom_point(aes(colour = genotype), size=1.75) +
        geom_smooth(method=lm, formula = y ~ poly(x,2), se=TRUE, 
                    aes(group = genotype, colour = genotype), fill='#DDDDDD', size=0.5) +
        #facet_grid(. ~ genotype) +
        xlab(label = "Olaparib (log10 nM)") +
        ylab(label = "Normalized Counts") +
        scale_color_manual(values=c('#000000','#800000','#000080','#008080','#808080'))

dev.off()



```


## Models


```{r}
library(DHARMa)
library(lme4)
library(lmerTest)
library(bbmle)
```

### Linear formula

```{r}
fit1 <- lm(Counts ~ Experiment + Olaparib*genotype, data = dataset)
print(summary(fit1))
cat("AIC: ", AIC(fit1))

simres <- simulateResiduals(fittedModel = fit1)
plot(simres)
```

```{r}
fit2 <- lm(NormCounts ~ Olaparib*genotype, data = dataset)
print(summary(fit2))
cat("AIC: ", AIC(fit2))

simres <- simulateResiduals(fittedModel = fit2)
plot(simres)
```

```{r}
fit3 <- lm(NormCounts2 ~ Olaparib*genotype, data = dataset)
print(summary(fit3))
cat("AIC: ", AIC(fit3))

simres <- simulateResiduals(fittedModel = fit3)
plot(simres)
```


```{r}
fit4 <- lmer(Counts ~ Olaparib*genotype + (1|UID), data = dataset)
print(summary(fit4))
cat("AIC: ", AIC(fit4))

simres <- simulateResiduals(fittedModel = fit4)
plot(simres)
```



### Quadratic formula

```{r}
fit5 <- lm(Counts ~ Experiment + poly(Olaparib, 2)*genotype, data = dataset)
print(summary(fit5))
cat("AIC: ", AIC(fit5))

simres <- simulateResiduals(fittedModel = fit5)
plot(simres)
```

```{r}
fit6 <- lm(NormCounts ~ poly(Olaparib, 2)*genotype, data = dataset)
print(summary(fit6))
cat("AIC: ", AIC(fit6))

simres <- simulateResiduals(fittedModel = fit6)
plot(simres)
```

```{r}
fit7 <- lm(NormCounts2 ~ poly(Olaparib, 2)*genotype, data = dataset)
print(summary(fit7))
cat("AIC: ", AIC(fit7))

simres <- simulateResiduals(fittedModel = fit7)
plot(simres)
```


```{r}
fit8 <- lmer(Counts ~ poly(Olaparib, 2)*genotype + (1|UID), data = dataset)
print(summary(fit8))
cat("AIC: ", AIC(fit8))

simres <- simulateResiduals(fittedModel = fit8)
plot(simres)
```



### Cubic formula

```{r}
fit9 <- lm(Counts ~ Experiment + poly(Olaparib, 3)*genotype, data = dataset)
print(summary(fit9))
cat("AIC: ", AIC(fit9))

simres <- simulateResiduals(fittedModel = fit9)
plot(simres)
```

```{r}
fit10 <- lm(NormCounts ~ poly(Olaparib, 3)*genotype, data = dataset)
print(summary(fit10))
cat("AIC: ", AIC(fit10))

simres <- simulateResiduals(fittedModel = fit10)
plot(simres)
```

```{r}
fit11 <- lm(NormCounts2 ~ poly(Olaparib, 3)*genotype, data = dataset)
print(summary(fit11))
cat("AIC: ", AIC(fit11))

simres <- simulateResiduals(fittedModel = fit11)
plot(simres)
```


```{r}
fit12 <- lmer(Counts ~ poly(Olaparib, 3)*genotype + (1|UID), data = dataset)
print(summary(fit12))
cat("AIC: ", AIC(fit12))

simres <- simulateResiduals(fittedModel = fit12)
plot(simres)
```


# Compare Results


```{r}
ICtab(fit1,fit2,fit3,fit4,
      fit5,fit6,fit7,fit8,
      fit9,fit10,fit11,fit12,
      base=T)
```



# Final Result

```{r, fig.height=5, fig.width=18}
fit <- fit7

output <- coef(summary(fit))
output <- output[grep("Olaparib", rownames(output)),]

rownames(output) <- gsub("poly\\(|, [1-3]\\)","", rownames(output) )
rownames(output) <- gsub("genotype",  paste0(" ",levels(dataset$genotype)[1], " vs. "), rownames(output))
rownames(output)[!(grepl("vs", rownames(output)))] <- paste(rownames(output)[!(grepl("vs", rownames(output)))], levels(dataset$genotype)[1],  sep = " in " )

# suggested result table
kable(output, row.names = T)

write.table(output, file = "Figure1D_Stats_Ref_WT.txt", quote = F, sep = "\t", row.names = T, col.names = NA)
```



```{r, fig.height=5, fig.width=18}
# re-fit with ALC1KO reference
dataset$genotype <- relevel(dataset$genotype, ref = "ALC1 KO #1")
        
fit <- lm(NormCounts2 ~ poly(Olaparib, 2)*genotype, data = dataset)


output <- coef(summary(fit))
output <- output[grep("Olaparib", rownames(output)),]

rownames(output) <- gsub("poly\\(|, [1-3]\\)","", rownames(output) )
rownames(output) <- gsub("genotype",  paste0(" ",levels(dataset$genotype)[1], " vs. "), rownames(output))
rownames(output)[!(grepl("vs", rownames(output)))] <- paste(rownames(output)[!(grepl("vs", rownames(output)))], levels(dataset$genotype)[1],  sep = " in " )

# suggested result table
kable(output, row.names = T)

write.table(output, file = "Figure1D_Stats_Ref_ALC1.txt", quote = F, sep = "\t", row.names = T, col.names = NA)
```



# Anova

```{r}
fit7a <- lm(NormCounts2 ~ poly(Olaparib, 2)*genotype, data = dataset)
fit7b <- lm(NormCounts2 ~ poly(Olaparib, 2)+genotype, data = dataset)

# anova table
anova(fit7a, fit7b)
```


