---
title: "FigureS2E"
output: html_document
---


<style>
pre {
  overflow-x: auto;
}
pre code {
  word-wrap: normal;
  white-space: pre;
}
.table{
  width:auto;
  font-size: 10px;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE, results=TRUE, fig.align='center', fig.height=5, fig.width=8)
library(knitr)
```


## Load Data


```{r}
library(gdata)
dataset <- read.delim("raw_data/FigureS2E.txt", stringsAsFactors = FALSE)

dataset$experiment <- factor(rep(paste0("exp", 1:3), each= 100))

#kable(dataset, row.names = F)

library(reshape2)
# reshape to long format
dataset <- melt(dataset, variable.name = "group", value.name = "Outcome")

dataset$group <- factor(gsub("\\.|U2OS","",dataset$group))

dataset$genotype <- factor(gsub("_.*", "", dataset$group))
dataset$treatment <- factor(gsub("OP","Olaparib",gsub(".*_", "", dataset$group)))

dataset$genotype <- relevel(dataset$genotype, ref = "WT")
dataset$treatment <- relevel(dataset$treatment, ref = "NT")



datamean <- aggregate(Outcome ~ genotype+treatment+experiment, data = dataset, mean)
datamean$group <- paste(datamean$genotype, datamean$treatment, sep = "_")
datamean$group <- factor(datamean$group, levels = unique(datamean$group))

kable(datamean, row.names = F)
```


## Plot Data


```{r, fig.height=5, fig.width=6}
library(ggplot2)



ggplot(dataset, aes(x=group, y=Outcome)) + 
        theme_bw() +
        theme(panel.grid=element_blank(), text = element_text(size=14), axis.text.x = element_text(angle = 90, hjust = 1)) +
        geom_jitter(aes(shape=genotype, color=experiment), size=2) +        
        scale_shape_manual(values=15:20) +
        scale_color_manual(values=c("#00000080","#00008080","#80000080"))



dataplot <- aggregate(Outcome ~ genotype+treatment, data = datamean, mean)
dataplot$se <- aggregate(Outcome ~ genotype+treatment, data = datamean, FUN = function(x){ sd(x)/sqrt(length(x))})$Outcome
dataplot$group <- paste(dataplot$genotype, dataplot$treatment, dataplot$Xray, sep = "_")
dataplot$group <- factor(dataplot$group, levels = dataplot$group )



ggplot(dataplot, aes(x=group, y=Outcome, fill = genotype)) + 
        theme_bw() +
        theme(panel.grid=element_blank(), text = element_text(size=14), axis.text.x = element_text(angle = 90, hjust = 1)) +
        geom_bar(stat="identity", position=position_dodge()) +
        geom_errorbar(aes(ymin=Outcome-se, ymax=Outcome+se),width=.2, position=position_dodge(.9)) +
        ylab(label = "Comet") +
        scale_fill_manual(values=c("#000000","#0000A0"))


datamean$logOutcome <- log(datamean$Outcome)

dataplot$logOutcome <- aggregate(logOutcome ~ genotype+treatment, data = datamean, mean)$logOutcome
dataplot$logse <- aggregate(logOutcome ~ genotype+treatment, data = datamean, FUN = function(x){ sd(x)/sqrt(length(x))})$logOutcome


ggplot(dataset, aes(x=group, y=log(Outcome))) + 
        theme_bw() +
        theme(panel.grid=element_blank(), text = element_text(size=14), axis.text.x = element_text(angle = 90, hjust = 1)) +
        geom_jitter(aes(shape=genotype, color=experiment), size=2) +        
        scale_shape_manual(values=15:20) +
        scale_color_manual(values=c("#00000080","#00008080","#80000080"))


ggplot(dataplot, aes(x=group, y=logOutcome, fill = genotype)) + 
        theme_bw() +
        theme(panel.grid=element_blank(), text = element_text(size=14), axis.text.x = element_text(angle = 90, hjust = 1)) +
        geom_bar(stat="identity", position=position_dodge()) +
        geom_errorbar(aes(ymin=logOutcome-logse, ymax=logOutcome+logse),width=.2, position=position_dodge(.9)) +
        ylab(label = "Comet") +
        scale_fill_manual(values=c("#000000","#0000A0"))



library(Cairo)

cairo_pdf("FigureS2E_v1.pdf", width = 6, height = 5, family = "Arial")

ggplot(dataplot, aes(x=treatment, y=Outcome, fill = genotype)) + 
        theme_bw() +
        theme(panel.grid.major=element_blank(), panel.grid.minor=element_blank(), 
              axis.line = element_line(colour = "black"), text = element_text(size=14),
              panel.border = element_blank(), panel.background = element_blank()) +
        geom_bar(stat="identity", position=position_dodge()) +
        geom_errorbar(aes(ymin=Outcome-se, ymax=Outcome+se),width=.2, position=position_dodge(.9)) +
        ylab(label = "comet tail length (µm)") +
        scale_fill_manual(values=c("#000000","#0000A0"))


dev.off()



library(Cairo)


cairo_pdf("FigureS2E_v2.pdf", width = 6, height = 5, family = "Arial")

ggplot(dataplot, aes(x=treatment, y=Outcome, fill = genotype)) + 
        theme_bw() +
        theme(panel.grid.major=element_blank(), panel.grid.minor=element_blank(), 
              axis.line = element_line(colour = "black"), text = element_text(size=14),
              panel.border = element_blank(), panel.background = element_blank()) +
        geom_bar(stat="identity", position=position_dodge(), colour="black") +
        ylab(label = "comet tail length (µm)") +
        scale_fill_manual(values=c("#00000080","#0000A080")) +
        geom_jitter(data = datamean, cex=1, position=position_dodge(0.9),  aes(colour=genotype)) +
        scale_color_manual(values=c("#000000","#0000A0")) +
        geom_errorbar(aes(ymin=Outcome-se, ymax=Outcome+se),width=.2, position=position_dodge(.9))


dev.off()



cairo_pdf("FigureS2E_v2_log.pdf", width = 6, height = 5, family = "Arial")

ggplot(dataplot, aes(x=treatment, y=logOutcome, fill = genotype)) + 
        theme_bw() +
        theme(panel.grid.major=element_blank(), panel.grid.minor=element_blank(), 
              axis.line = element_line(colour = "black"), text = element_text(size=14),
              panel.border = element_blank(), panel.background = element_blank()) +
        geom_bar(stat="identity", position=position_dodge(), colour="black") +
        ylab(label = "comet tail length (log µm)") +
        scale_fill_manual(values=c("#00000080","#0000A080")) +
        geom_jitter(data = datamean, cex=1, position=position_dodge(0.9),  aes(colour=genotype)) +
        scale_color_manual(values=c("#000000","#0000A0")) + 
        coord_cartesian(ylim=c(2.5,4.5)) +
        geom_errorbar(aes(ymin=logOutcome-logse, ymax=logOutcome+logse),width=.2, position=position_dodge(.9))


dev.off()


cairo_pdf("FigureS2E_v3.pdf", width = 6, height = 5, family = "Arial")

ggplot(datamean, aes(x=treatment, y=Outcome, color=genotype)) + 
        theme_bw() +
        theme(panel.grid.major=element_blank(), panel.grid.minor=element_blank(), 
              axis.line = element_line(colour = "black"), text = element_text(size=14),
              panel.border = element_blank(), panel.background = element_blank()) +
        geom_jitter(cex=1, position=position_dodge(1)) + 
        stat_summary(fun.data=mean_se, fun.args = list(mult=1), geom="errorbar", width=0.25, aes(colour=genotype), position=position_dodge(1)) +
        stat_summary(fun.y=mean, geom="crossbar", width=0.5, aes(colour=genotype), position=position_dodge(1)) +
        ylab(label = "comet tail length (µm)") +
        scale_fill_manual(values=c("#000000","#0000A0")) +
        scale_color_manual(values=c("#000000","#0000A0"))


dev.off()


cairo_pdf("FigureS2E_v3_log.pdf", width = 6, height = 5, family = "Arial")

ggplot(datamean, aes(x=treatment, y=log(Outcome), color=genotype)) + 
        theme_bw() +
        theme(panel.grid.major=element_blank(), panel.grid.minor=element_blank(), 
              axis.line = element_line(colour = "black"), text = element_text(size=14),
              panel.border = element_blank(), panel.background = element_blank()) +
        geom_jitter(cex=1, position=position_dodge(1)) + 
        stat_summary(fun.data=mean_se, fun.args = list(mult=1), geom="errorbar", width=0.25, aes(colour=genotype), position=position_dodge(1)) +
        stat_summary(fun.y=mean, geom="crossbar", width=0.5, aes(colour=genotype), position=position_dodge(1)) +
        ylab(label = "comet tail length (µm)") +
        coord_cartesian(ylim=c(2.5,4.5)) +
        scale_fill_manual(values=c("#000000","#0000A0")) +
        scale_color_manual(values=c("#000000","#0000A0"))


dev.off()



```



## Linear Model


```{r}
library(MASS)
library(DHARMa)
library(lme4)
library(lmerTest)
library(bbmle)
```


```{r}
fit1 <- lm(log(Outcome) ~ experiment + genotype*treatment, data = datamean)
print(summary(fit1))
cat("AIC: ", AIC(fit1))

simres <- simulateResiduals(fittedModel = fit1)
plot(simres)
```


```{r}
fit2 <- lm(Outcome ~ experiment + genotype*treatment, data = datamean)
print(summary(fit2))
cat("AIC: ", AIC(fit2))

simres <- simulateResiduals(fittedModel = fit2)
plot(simres)
```

```{r}
fit3 <- lmer(Outcome ~ + genotype*treatment + (1|experiment), data = dataset)
print(summary(fit3))
cat("AIC: ", AIC(fit3))

simres <- simulateResiduals(fittedModel = fit3)
plot(simres)
```


## Compare Results


```{r}
ICtab(fit1,fit2,fit3,
      base=T)
```

## Final Result

```{r, fig.height=5, fig.width=18}
fit <- fit1

output <- coef(summary(fit))
output <- output[grep("treatment|genotype", rownames(output)),]

rownames(output)[grepl("genotype", rownames(output))&!grepl("\\:",rownames(output))] <- 
        paste0(rownames(output)[grepl("genotype", rownames(output))&!grepl("\\:",rownames(output))], " in ", levels(datamean$treatment)[1])

rownames(output)[grepl("treatment",rownames(output))&!grepl("\\:",rownames(output))] <- 
        paste0(rownames(output)[grepl("treatment",rownames(output))&!grepl("\\:",rownames(output))], " in ", levels(datamean$genotype)[1])

rownames(output) <- gsub("genotype",   paste0(" ",levels(datamean$genotype)[1], " vs. "), rownames(output))
rownames(output) <- gsub("treatment",  paste0(" ",levels(datamean$treatment)[1], " vs. "), rownames(output))


# suggested result table
kable(output, row.names = T)

write.table(output, file = "FigureS2E_Stats_Ref_WT_NT.txt", quote = F, sep = "\t", row.names = T, col.names = NA)
```

```{r, fig.height=5, fig.width=18}
# re-fit with ALC1KO reference
datamean$genotype <- relevel(datamean$genotype, ref = "ALC1KO")

fit <- lm(log(Outcome) ~ experiment + treatment*genotype, data = datamean)

output <- coef(summary(fit))
output <- output[grep("treatment|genotype", rownames(output)),]

rownames(output)[grepl("genotype", rownames(output))&!grepl("\\:",rownames(output))] <- 
        paste0(rownames(output)[grepl("genotype", rownames(output))&!grepl("\\:",rownames(output))], " in ", levels(datamean$treatment)[1])

rownames(output)[grepl("treatment",rownames(output))&!grepl("\\:",rownames(output))] <- 
        paste0(rownames(output)[grepl("treatment",rownames(output))&!grepl("\\:",rownames(output))], " in ", levels(datamean$genotype)[1])

rownames(output) <- gsub("genotype",   paste0(" ",levels(datamean$genotype)[1], " vs. "), rownames(output))
rownames(output) <- gsub("treatment",  paste0(" ",levels(datamean$treatment)[1], " vs. "), rownames(output))


# suggested result table
kable(output, row.names = T)

write.table(output, file = "FigureS2E_Stats_Ref_ALC1_NT.txt", quote = F, sep = "\t", row.names = T, col.names = NA)
```

```{r, fig.height=5, fig.width=18}
# re-fit with Olaparib reference
datamean$genotype <- relevel(datamean$genotype, ref = "WT")
datamean$treatment <- relevel(datamean$treatment, ref = "Olaparib")

fit <- lm(log(Outcome) ~ experiment + treatment*genotype, data = datamean)

output <- coef(summary(fit))
output <- output[grep("treatment|genotype", rownames(output)),]

rownames(output)[grepl("genotype", rownames(output))&!grepl("\\:",rownames(output))] <- 
        paste0(rownames(output)[grepl("genotype", rownames(output))&!grepl("\\:",rownames(output))], " in ", levels(datamean$treatment)[1])

rownames(output)[grepl("treatment",rownames(output))&!grepl("\\:",rownames(output))] <- 
        paste0(rownames(output)[grepl("treatment",rownames(output))&!grepl("\\:",rownames(output))], " in ", levels(datamean$genotype)[1])

rownames(output) <- gsub("genotype",   paste0(" ",levels(datamean$genotype)[1], " vs. "), rownames(output))
rownames(output) <- gsub("treatment",  paste0(" ",levels(datamean$treatment)[1], " vs. "), rownames(output))


# suggested result table
kable(output, row.names = T)

write.table(output, file = "FigureS2E_Stats_Ref_WT_Olaparib.txt", quote = F, sep = "\t", row.names = T, col.names = NA)
```

## ANOVA


```{r}
fit1a <- lm(log(Outcome) ~ experiment + treatment*genotype, data = datamean)
fit1b <- lm(log(Outcome) ~ experiment + treatment+genotype, data = datamean)

anova(fit1a, fit1b)

```

