---
title: "Figure2C"
output: html_document
---


<style>
pre {
  overflow-x: auto;
}
pre code {
  word-wrap: normal;
  white-space: pre;
}
.table{
  width:auto;
  font-size: 10px;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE, results=TRUE, fig.align='center', fig.height=5, fig.width=8)
library(knitr)
```


## Load Data


```{r}
library(gdata)
dataset <- read.delim("raw_data/Figure2C.txt", stringsAsFactors = FALSE)

dataset$genotype <- factor(gsub(" ","",dataset$genotype))
dataset$experiment <- factor(rep(paste0("exp", 1:(length(dataset$genotype)/length(levels(dataset$genotype)))), each= length(levels(dataset$genotype))))

dataset$UID <- factor(paste(dataset$experiment, dataset$genotype))

kable(dataset, row.names = F)


library(reshape2)
# reshape to long format
dataset <- melt(dataset, variable.name = "treatment", value.name = "Outcome")

dataset$genotype <- relevel(dataset$genotype, ref = "WT")
dataset$UID <- relevel(dataset$UID, ref = "exp1 WT")


dataset$olaparib <- gsub("NT","1",dataset$treatment)
dataset$olaparib <- gsub("X|nM","",dataset$olaparib)
dataset$olaparib <- log10(as.integer(dataset$olaparib))



dataset$Offset <- NA
for(uid in levels(dataset$UID)){
        dataset$Offset[dataset$UID == uid] <- mean(dataset$Outcome[dataset$UID == uid])
}

dataset$NormOutcome <- dataset$Outcome / dataset$Offset



dataset$Offset2 <- NA
for(gid in levels(dataset$genotype)){
        dataset$Offset2[dataset$genotype == gid] <- mean(dataset$NormOutcome[dataset$genotype == gid & dataset$olaparib == 0])
}

dataset$NormOutcome2 <- dataset$NormOutcome / dataset$Offset2




kable(dataset, row.names = F)
```


## Plot Data


```{r, fig.height=5, fig.width=10}
library(ggplot2)

# raw data
ggplot(dataset, aes(x=olaparib, y=Outcome)) + 
        theme_bw() +
        theme(panel.grid=element_blank(), text = element_text(size=14)) +
        geom_smooth(method=lm, formula = y ~ poly(x,2), se=FALSE, aes(colour=genotype)) +
        geom_point(aes(colour=genotype, shape=experiment), size=2) +        
        facet_grid(. ~ genotype) +
        xlab(label = "Olaparib (log10 nM)") +
        scale_shape_manual(values=15:20) +
        scale_color_manual(values=c("#000000","#000080","#808080","#800000"))

# norm
ggplot(dataset, aes(x=olaparib, y=NormOutcome)) + 
        theme_bw() +
        theme(panel.grid=element_blank(), text = element_text(size=14)) +
        geom_smooth(method=lm, formula = y ~ poly(x,2), se=FALSE, aes(colour=genotype)) +
        geom_point(aes(colour=genotype, shape=experiment), size=2) +        
        facet_grid(. ~ genotype) +
        xlab(label = "Olaparib (log10 nM)") +
        scale_shape_manual(values=15:20) +
        scale_color_manual(values=c("#000000","#000080","#808080","#800000"))

# norm2
ggplot(dataset, aes(x=olaparib, y=NormOutcome2)) + 
        theme_bw() +
        theme(panel.grid=element_blank(), text = element_text(size=14)) +
        geom_smooth(method=lm, formula = y ~ poly(x,2), se=FALSE, aes(colour=genotype)) +
        geom_point(aes(colour=genotype, shape=experiment), size=2) +        
        facet_grid(. ~ genotype) +
        xlab(label = "Olaparib (log10 nM)") +
        scale_shape_manual(values=15:20) +
        scale_color_manual(values=c("#000000","#000080","#808080","#800000"))


dataplot <- aggregate(NormOutcome2 ~ genotype+treatment, data = dataset, mean)
dataplot$se <- aggregate(NormOutcome2 ~ genotype+treatment, data = dataset, FUN = function(x){ sd(x)/sqrt(length(x))})$NormOutcome2
dataplot$treatment <- factor(gsub("X|.nM","", dataplot$treatment)) 

dataplot$genotype <- factor(dataplot$genotype, levels = c("WT","PARP1KO","ALC1KO","ALC1KOPARP1KO"))
dataplot$treatment <- relevel(dataplot$treatment, ref = "NT")


ggplot(dataplot, aes(x=treatment, y=NormOutcome2, fill = genotype)) + 
        theme_bw() +
        theme(panel.grid=element_blank(), text = element_text(size=14)) +
        geom_bar(stat="identity", position=position_dodge()) +
        geom_errorbar(aes(ymin=NormOutcome2-se, ymax=NormOutcome2+se),width=.2, position=position_dodge(.9)) +
        ylab(label = paste0("Relative ",expression("\u03B3"),"H2AX intensity")) +
        xlab(label = "Olaparib (nM)") +
        ylim(0, 6) +
        scale_fill_manual(values=c("#000000","#800000","#000080","#808080"))

library(Cairo)
cairo_pdf("Figure2C_v1.pdf", width = 8, height = 4)

ggplot(dataplot, aes(x=treatment, y=NormOutcome2, fill = genotype)) + 
        theme_bw() +
        theme(panel.grid=element_blank(), text = element_text(size=14)) +
        geom_bar(stat="identity", position=position_dodge()) +
        geom_errorbar(aes(ymin=NormOutcome2-se, ymax=NormOutcome2+se),width=.2, position=position_dodge(.9)) +
        ylab(label = paste0("Relative ",expression("\u03B3"),"H2AX intensity")) +
        xlab(label = "Olaparib (nM)") +
        ylim(0, 6) +
        scale_fill_manual(values=c("#000000","#800000","#000080","#808080"))

dev.off()




dataset$genotype <- factor(dataset$genotype, levels = c("WT","PARP1KO","ALC1KO","ALC1KOPARP1KO"))
dataset$treatment <- relevel(dataset$treatment, ref = "NT")
dataset$treatment <- factor(gsub("X|.nM","", dataset$treatment), levels =c("NT","30","300","3000","30000") ) 


cairo_pdf("Figure2C_v2.pdf", width = 8, height = 4)

ggplot(dataplot, aes(x=treatment, y=NormOutcome2, fill = genotype)) + 
        theme_bw() +
        theme(panel.grid=element_blank(), text = element_text(size=14)) +
        geom_bar(stat="identity", position=position_dodge(), colour="black") +
        ylab(label = paste0("Relative ",expression("\u03B3"),"H2AX intensity")) +
        xlab(label = "Olaparib (nM)") +
        ylim(0, 6) +
        scale_fill_manual(values=c("#00000080","#80000080","#00008080","#80808080")) +
        geom_jitter(data = dataset, cex=1, position=position_dodge(0.9),  aes(colour=genotype)) +
        scale_color_manual(values=c("#000000","#800000","#000080","#808080")) +
        geom_errorbar(aes(ymin=NormOutcome2-se, ymax=NormOutcome2+se),width=.2, position=position_dodge(.9)) 

dev.off()


cairo_pdf("Figure2C_v3.pdf", width = 8, height = 4)

ggplot(dataset, aes(x=treatment, y=NormOutcome2, color=genotype)) + 
        theme_bw() +
        theme(panel.grid=element_blank(), text = element_text(size=14)) +
        geom_jitter(cex=1, position=position_dodge(1)) + 
        stat_summary(fun.data=mean_se, fun.args = list(mult=1), geom="errorbar", width=0.25, aes(colour=genotype), position=position_dodge(1)) +
        stat_summary(fun.y=mean, geom="crossbar", width=0.5, aes(colour=genotype), position=position_dodge(1)) +
        ylab(label = paste0("Relative ",expression("\u03B3"),"H2AX intensity")) +
        xlab(label = "Olaparib (nM)") +
        ylim(0, 6) +
        scale_fill_manual(values=c("#000000","#800000","#000080","#808080")) +
        scale_color_manual(values=c("#000000","#800000","#000080","#808080"))

dev.off()





```



## Linear Model


```{r}
library(MASS)
library(DHARMa)
library(lme4)
library(lmerTest)
library(bbmle)
```


```{r}
fit1 <- lm(NormOutcome2 ~ olaparib*genotype, data = dataset)
print(summary(fit1))
cat("AIC: ", AIC(fit1))

simres <- simulateResiduals(fittedModel = fit1)
plot(simres)
```


```{r}
fit2 <- lm(NormOutcome2 ~ poly(olaparib,2)*genotype, data = dataset)
print(summary(fit2))
cat("AIC: ", AIC(fit2))

simres <- simulateResiduals(fittedModel = fit2)
plot(simres)
```


```{r}
fit3 <- lm(NormOutcome2 ~ poly(olaparib,3)*genotype, data = dataset)
print(summary(fit3))
cat("AIC: ", AIC(fit3))

simres <- simulateResiduals(fittedModel = fit3)
plot(simres)
```





## Compare Results


```{r}
ICtab(fit1,fit2,
      fit3,
      base=T)
```

## Final Result

```{r, fig.height=5, fig.width=18}
fit <- fit2

output <- coef(summary(fit))
output <- output[grep("olaparib", rownames(output)),]

rownames(output) <- gsub("poly\\(|, [1-3]\\)","", rownames(output) )
rownames(output) <- gsub("genotype",  paste0(" ",levels(dataset$genotype)[1], " vs. "), rownames(output))
rownames(output)[!(grepl("vs", rownames(output)))] <- paste(rownames(output)[!(grepl("vs", rownames(output)))], levels(dataset$genotype)[1],  sep = " in " )


# suggested result table
kable(output, row.names = T)

write.table(output, file = "Figure2C_Stats_Ref_WT.txt", quote = F, sep = "\t", row.names = T, col.names = NA)
```

```{r, fig.height=5, fig.width=18}
# re-fit with ALC1KO reference
dataset$genotype <- relevel(dataset$genotype, ref = "ALC1KO")

fit <- lm(NormOutcome2 ~ poly(olaparib,2)*genotype, data = dataset)

output <- coef(summary(fit))
output <- output[grep("olaparib", rownames(output)),]

rownames(output) <- gsub("poly\\(|, [1-3]\\)","", rownames(output) )
rownames(output) <- gsub("genotype",  paste0(" ",levels(dataset$genotype)[1], " vs. "), rownames(output))
rownames(output)[!(grepl("vs", rownames(output)))] <- paste(rownames(output)[!(grepl("vs", rownames(output)))], levels(dataset$genotype)[1],  sep = " in " )


# suggested result table
kable(output, row.names = T)

write.table(output, file = "Figure2C_Stats_Ref_ALC1KO.txt", quote = F, sep = "\t", row.names = T, col.names = NA)
```



## ANOVA


```{r}
fit2a <- lm(NormOutcome2 ~ poly(olaparib,2)*genotype, data = dataset)
fit2b <- lm(NormOutcome2 ~ poly(olaparib,2)+genotype, data = dataset)

anova(fit2a, fit2b)

```

