---
title: "FigureS4A"
output: html_document
---


<style>
pre {
  overflow-x: auto;
}
pre code {
  word-wrap: normal;
  white-space: pre;
}
.table{
  width:auto;
  font-size: 10px;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE, results=TRUE, fig.align='center', fig.height=5, fig.width=8)
library(knitr)
```


## Load Data


```{r}
library(gdata)
dataset <- read.delim("raw_data/FigureS4A.txt", stringsAsFactors = FALSE)

dataset$genotype <- factor(gsub(" ","",dataset$genotype))
dataset$experiment <- factor(rep(paste0("exp", 1:(length(dataset$genotype)/length(levels(dataset$genotype)))), each= length(levels(dataset$genotype))))

dataset$UID <- factor(paste(dataset$experiment, dataset$genotype))


kable(dataset, row.names = F)


library(reshape2)
# reshape to long format
dataset <- melt(dataset, variable.name = "treatment", value.name = "Outcome")

dataset$group <- factor(paste(dataset$genotype, dataset$treatment, sep="+"))

dataset$genotype <-  relevel(dataset$genotype, ref = "siCtrl")
dataset$treatment <- relevel(dataset$treatment, ref = "NT")


dataset$Offset <- NA
for(uid in levels(dataset$UID)){
        dataset$Offset[dataset$UID == uid] <- mean(dataset$Outcome[dataset$UID == uid])
}

dataset$NormOutcome <- dataset$Outcome / dataset$Offset



dataset$Offset2 <- NA
for(gid in levels(dataset$genotype)){
        dataset$Offset2[dataset$genotype == gid] <- mean(dataset$NormOutcome[dataset$genotype == gid & dataset$treatment == "NT"])

}

dataset$NormOutcome2 <- dataset$NormOutcome / dataset$Offset2


kable(dataset, row.names = F)
```


## Plot Data


```{r, fig.height=5, fig.width=6}
library(ggplot2)

# raw data
ggplot(dataset, aes(x=group, y=Outcome)) + 
        theme_bw() +
        theme(panel.grid=element_blank(), text = element_text(size=14), axis.text.x = element_text(angle = 90, hjust = 1)) +
        geom_point(aes(colour=genotype, shape=experiment), size=2) +        
        scale_shape_manual(values=15:20) +
        scale_color_manual(values=c("#000000","#0000A0","#A00000"))

# norm data
ggplot(dataset, aes(x=group, y=NormOutcome)) + 
        theme_bw() +
        theme(panel.grid=element_blank(), text = element_text(size=14), axis.text.x = element_text(angle = 90, hjust = 1)) +
        geom_point(aes(colour=genotype, shape=experiment), size=2) +        
        scale_shape_manual(values=15:20) +
        scale_color_manual(values=c("#000000","#0000A0","#A00000"))

# norm2 data
ggplot(dataset, aes(x=group, y=NormOutcome2)) + 
        theme_bw() +
        theme(panel.grid=element_blank(), text = element_text(size=14), axis.text.x = element_text(angle = 90, hjust = 1)) +
        geom_point(aes(colour=genotype, shape=experiment), size=2) +        
        scale_shape_manual(values=15:20) +
        scale_color_manual(values=c("#000000","#0000A0","#A00000"))


dataplot <- aggregate(NormOutcome2 ~ genotype+treatment, data = dataset, mean)
dataplot$se <- aggregate(NormOutcome2 ~ genotype+treatment, data = dataset, FUN = function(x){ sd(x)/sqrt(length(x))})$NormOutcome2

dataplot$genotype <- factor(dataplot$genotype, levels = c("siCtrl", "siBRCA1", "siALC1"))
dataplot$treatment <- relevel(dataplot$treatment, ref = "NT")

ggplot(dataplot, aes(x=genotype, y=NormOutcome2, fill = treatment)) + 
        theme_bw() +
        theme(panel.grid=element_blank(), text = element_text(size=14)) +
        geom_bar(stat="identity", position=position_dodge()) +
        geom_errorbar(aes(ymin=NormOutcome2-se, ymax=NormOutcome2+se),width=.2, position=position_dodge(.9)) +
        ylab(label = "chromatin fraction") +
        ylim(0, 3) +
        scale_fill_manual(values=c("#000000","#A00000","#0000A0"))


pdf("FigureS4A_v1.pdf", width = 5, height = 4)

ggplot(dataplot, aes(x=genotype, y=NormOutcome2, fill=treatment)) + 
        theme_bw() +
        theme(panel.grid=element_blank(), text = element_text(size=14)) +
        geom_bar(stat="identity", position=position_dodge()) +
        geom_errorbar(aes(ymin=NormOutcome2-se, ymax=NormOutcome2+se),width=.2, position=position_dodge(.9)) +
        ylab(label = "rel. chromatin fraction") +
        ylim(0, 3) +
        scale_fill_manual(values=c("#000000","#A00000","#0000A0"))

dev.off()



dataset$genotype <- factor(dataset$genotype, levels = c("siCtrl", "siBRCA1", "siALC1"))
dataset$treatment <- relevel(dataset$treatment, ref = "NT")

library(Cairo)

cairo_pdf("FigureS4A_v2.pdf", width = 5, height = 4)

ggplot(dataplot, aes(x=genotype, y=NormOutcome2, fill=treatment)) + 
        theme_bw() +
        theme(panel.grid=element_blank(), text = element_text(size=14)) +
        geom_bar(stat="identity", position=position_dodge(), colour="black") +
        ylab(label = "rel. chromatin fraction") +
        ylim(0, 3) +
        scale_fill_manual(values=c("#00000080","#A0000080","#0000A080")) +
        geom_jitter(data = dataset, cex=1, position=position_dodge(0.9),  aes(colour=treatment)) +
        scale_color_manual(values=c("#000000","#A00000","#0000A0")) +
        geom_errorbar(aes(ymin=NormOutcome2-se, ymax=NormOutcome2+se),width=.2, position=position_dodge(.9))


dev.off()


cairo_pdf("FigureS4A_v3.pdf", width = 5, height = 4)

ggplot(dataset, aes(x=genotype, y=NormOutcome2, color=treatment)) + 
        theme_bw() +
        theme(panel.grid=element_blank(), text = element_text(size=14)) + 
        geom_jitter(cex=1, position=position_dodge(1)) + 
        stat_summary(fun.data=mean_se, fun.args = list(mult=1), geom="errorbar", width=0.25, aes(colour=treatment), position=position_dodge(1)) +
        stat_summary(fun.y=mean, geom="crossbar", width=0.5, aes(colour=treatment), position=position_dodge(1)) +
        ylab(label = "rel. chromatin fraction") +
        ylim(0, 3) +
        scale_color_manual(values=c("#000000","#A00000","#0000A0")) 


dev.off()

```



## Linear Model


```{r}
library(MASS)
library(DHARMa)
library(lme4)
library(lmerTest)
library(bbmle)
```


```{r}
fit1 <- lm(NormOutcome2 ~ treatment*genotype, data = dataset)
print(summary(fit1))
cat("AIC: ", AIC(fit1))

simres <- simulateResiduals(fittedModel = fit1, n = 200)
plot(simres)
```

```{r}
fit2 <- lmer(NormOutcome2 ~ treatment*genotype + (1|experiment), data = dataset)
print(summary(fit2))
cat("AIC: ", AIC(fit2))

simres <- simulateResiduals(fittedModel = fit2)
plot(simres)
```


## Compare Results


```{r}
ICtab(fit1,fit2,
      base=T)
```

## Final Result

```{r, fig.height=5, fig.width=18}
fit <- fit1

output <- coef(summary(fit))
output <- output[grep("treatment|genotype", rownames(output)),]

rownames(output)[grepl("genotype", rownames(output))&!grepl("\\:",rownames(output))] <- 
        paste0(rownames(output)[grepl("genotype", rownames(output))&!grepl("\\:",rownames(output))], " in ", levels(dataset$treatment)[1])

rownames(output)[grepl("treatment",rownames(output))&!grepl("\\:",rownames(output))] <- 
        paste0(rownames(output)[grepl("treatment",rownames(output))&!grepl("\\:",rownames(output))], " in ", levels(dataset$genotype)[1])

rownames(output) <- gsub("genotype",   paste0(" ",levels(dataset$genotype)[1], " vs. "), rownames(output))
rownames(output) <- gsub("treatment",  paste0(" ",levels(dataset$treatment)[1], " vs. "), rownames(output))


# suggested result table
kable(output, row.names = T)

write.table(output, file = "FigureS4A_Stats_Ref_WT.txt", quote = F, sep = "\t", row.names = T, col.names = NA)
```

```{r, fig.height=5, fig.width=18}
# re-fit with siALC1 reference
dataset$genotype <- relevel(dataset$genotype, ref = "siALC1")

fit <- lm(NormOutcome2 ~ treatment*genotype, data = dataset)


output <- coef(summary(fit))
output <- output[grep("treatment|genotype", rownames(output)),]

rownames(output)[grepl("genotype", rownames(output))&!grepl("\\:",rownames(output))] <- 
        paste0(rownames(output)[grepl("genotype", rownames(output))&!grepl("\\:",rownames(output))], " in ", levels(dataset$treatment)[1])

rownames(output)[grepl("treatment",rownames(output))&!grepl("\\:",rownames(output))] <- 
        paste0(rownames(output)[grepl("treatment",rownames(output))&!grepl("\\:",rownames(output))], " in ", levels(dataset$genotype)[1])

rownames(output) <- gsub("genotype",   paste0(" ",levels(dataset$genotype)[1], " vs. "), rownames(output))
rownames(output) <- gsub("treatment",  paste0(" ",levels(dataset$treatment)[1], " vs. "), rownames(output))


# suggested result table
kable(output, row.names = T)

write.table(output, file = "FigureS4A_Stats_Ref_ALC1.txt", quote = F, sep = "\t", row.names = T, col.names = NA)
```


```{r, fig.height=5, fig.width=18}
# re-fit with BRCA1 reference
dataset$genotype <- relevel(dataset$genotype, ref = "siBRCA1")

fit <- lm(NormOutcome2 ~ treatment*genotype, data = dataset)


output <- coef(summary(fit))
output <- output[grep("treatment|genotype", rownames(output)),]

rownames(output)[grepl("genotype", rownames(output))&!grepl("\\:",rownames(output))] <- 
        paste0(rownames(output)[grepl("genotype", rownames(output))&!grepl("\\:",rownames(output))], " in ", levels(dataset$treatment)[1])

rownames(output)[grepl("treatment",rownames(output))&!grepl("\\:",rownames(output))] <- 
        paste0(rownames(output)[grepl("treatment",rownames(output))&!grepl("\\:",rownames(output))], " in ", levels(dataset$genotype)[1])

rownames(output) <- gsub("genotype",   paste0(" ",levels(dataset$genotype)[1], " vs. "), rownames(output))
rownames(output) <- gsub("treatment",  paste0(" ",levels(dataset$treatment)[1], " vs. "), rownames(output))


# suggested result table
kable(output, row.names = T)

write.table(output, file = "FigureS4A_Stats_Ref_BRCA1.txt", quote = F, sep = "\t", row.names = T, col.names = NA)
```



## ANOVA


```{r}
fit1a <- lm(NormOutcome2 ~ treatment*genotype, data = dataset)
fit1b <- lm(NormOutcome2 ~ treatment+genotype, data = dataset)

anova(fit1a, fit1b)

```

