---
title: "Figure5H"
output: html_document
---


<style>
pre {
  overflow-x: auto;
}
pre code {
  word-wrap: normal;
  white-space: pre;
}
.table{
  width:auto;
  font-size: 10px;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE, results=TRUE, fig.align='center', fig.height=5, fig.width=8)
library(knitr)
```


## Load Data


```{r}
dataset <- read.delim("raw_data/Figure5H.txt", stringsAsFactors = FALSE)

dataset$genotype <- gsub("Δ","d",gsub(" ", "", dataset$genotype))
dataset$genotype <- factor(dataset$genotype)
dataset$Experiment <- factor(rep(paste0("exp", 1:(length(dataset$genotype)/length(levels(dataset$genotype)))), each=length(unique(dataset$genotype))))

dataset$BRCA <-  factor(gsub("\\+.*","",dataset$genotype))
dataset$Alc1 <-  factor(gsub(".*[T,1]\\+","",dataset$genotype))

dataset$UID <- factor(paste(dataset$Experiment, dataset$Alc1, dataset$BRCA))
dataset$GSID <- factor(paste(dataset$Alc1, dataset$BRCA))

# wide format
kable(dataset, row.names = F)

library(reshape2)
# reshape to long format
dataset <- melt(dataset, variable.name = "Treatment", value.name = "Counts")

dataset$Alc1 <- relevel(dataset$Alc1, ref = "GFP")
dataset$BRCA <- relevel(dataset$BRCA, ref = "h/d11")
dataset$UID <- relevel(dataset$UID, ref = "exp1 GFP h/d11")

dataset$Olaparib <- gsub("NT","1",dataset$Treatment)
dataset$Olaparib <- gsub("olaparib_|nM","",dataset$Olaparib)
dataset$Olaparib <- log10(as.integer(dataset$Olaparib))




dataset$Offset <- NA
for(uid in levels(dataset$UID)){
        dataset$Offset[dataset$UID == uid] <- mean(dataset$Counts[dataset$UID == uid])
}

dataset$NormCounts <- dataset$Counts / dataset$Offset



dataset$Offset2 <- NA
for(gsid in levels(dataset$GSID)){
        dataset$Offset2[dataset$GSID == gsid] <- mean(dataset$NormCounts[dataset$GSID == gsid & dataset$Olaparib == 0])
}

dataset$NormCounts2 <- dataset$NormCounts / dataset$Offset2



# long format
kable(dataset, row.names = F)
```


## Plot Data


```{r, fig.height=5, fig.width=12}
library(ggplot2)

# raw data
ggplot(dataset, aes(x=Olaparib, y=Counts)) + 
        theme_bw() +
        theme(panel.grid=element_blank(), text = element_text(size=14)) +
        geom_smooth(method=lm, formula = y ~ poly(x,2), se=FALSE, aes(colour=BRCA)) +
        geom_point(aes(colour=BRCA, shape=Experiment), size=2) +        
        facet_grid(. ~ Alc1) +
        xlab(label = "Olaparib (log10 nM)") +
        scale_shape_manual(values=15:20) +
        scale_color_manual(values=c("#000000","#FF0000"))
```


```{r, fig.height=4, fig.width=8}
# NormCounts Linear
ggplot(dataset, aes(x=Olaparib, y=NormCounts, color=BRCA)) + 
        theme_bw() +
        theme(panel.grid=element_blank(), text = element_text(size=14)) +
        geom_point(aes(colour=BRCA), size=2) +        
        geom_smooth(method=lm, formula = y ~ x, se=FALSE) +
        facet_grid(. ~ Alc1) +
        xlab(label = "Olaparib (log10 nM)") +
        scale_color_manual(values=c("#000000","#FF0000"))


# NormCounts2 Linear
ggplot(dataset, aes(x=Olaparib, y=NormCounts2, color=BRCA)) + 
        theme_bw() +
        theme(panel.grid=element_blank(), text = element_text(size=14)) +
        geom_point(aes(colour=BRCA), size=2) +        
        geom_smooth(method=lm, formula = y ~ x, se=FALSE) +
        facet_grid(. ~ Alc1) +
        xlab(label = "Olaparib (log10 nM)") +
        scale_color_manual(values=c("#000000","#FF0000"))


# NormCounts Quadratic
ggplot(dataset, aes(x=Olaparib, y=NormCounts, color=BRCA)) + 
        theme_bw() +
        theme(panel.grid=element_blank(), text = element_text(size=14)) +
        geom_point(aes(colour=BRCA), size=2) +        
        geom_smooth(method=lm, formula = y ~ poly(x,2), se=FALSE) +
        facet_grid(. ~ Alc1) +
        xlab(label = "Olaparib (log10 nM)")+
        scale_color_manual(values=c("#000000","#FF0000"))


# NormCounts2 Quadratic
ggplot(dataset, aes(x=Olaparib, y=NormCounts2, color=BRCA)) + 
        theme_bw() +
        theme(panel.grid=element_blank(), text = element_text(size=14)) +
        geom_point(aes(colour=BRCA), size=2) +        
        geom_smooth(method=lm, formula = y ~ poly(x,2), se=FALSE) +
        facet_grid(. ~ Alc1) +
        xlab(label = "Olaparib (log10 nM)") +
        scale_color_manual(values=c("#000000","#FF0000"))


# NormCounts Cubic
ggplot(dataset, aes(x=Olaparib, y=NormCounts, color=BRCA)) + 
        theme_bw() +
        theme(panel.grid=element_blank(), text = element_text(size=14)) +
        geom_point(aes(colour=BRCA), size=2) +        
        geom_smooth(method=lm, formula = y ~ poly(x,3), se=FALSE) +
        facet_grid(. ~ Alc1) +
        xlab(label = "Olaparib (log10 nM)")+
        scale_color_manual(values=c("#000000","#FF0000"))

 
# NormCounts2 Cubic
ggplot(dataset, aes(x=Olaparib, y=NormCounts2, color=BRCA)) + 
        theme_bw() +
        theme(panel.grid=element_blank(), text = element_text(size=14)) +
        geom_point(aes(colour=BRCA), size=2) +        
        geom_smooth(method=lm, formula = y ~ poly(x,3), se=FALSE) +
        facet_grid(. ~ Alc1) +
        xlab(label = "Olaparib (log10 nM)") +
        scale_color_manual(values=c("#000000","#FF0000"))


library(Cairo)


cairo_pdf("Figure5H.pdf", width = 5, height = 4, family = "Arial")

ggplot(dataset, aes(x=Olaparib, y=NormCounts2)) + 
        theme_bw() +
        theme(panel.grid.major=element_blank(), panel.grid.minor=element_blank(), 
              axis.line = element_line(colour = "black"), text = element_text(size=14),
              panel.border = element_blank(), panel.background = element_blank()) +
        geom_point(aes(colour = BRCA, shape = Alc1), size=1.75) +
        geom_smooth(method=lm, formula = y ~ poly(x,3), se=TRUE, 
                    aes(group = GSID,colour = BRCA, linetype = Alc1), fill='#DDDDDD', size=0.5) +
        xlab(label = "Olaparib (log10 nM)") +
        ylab(label = "Normalized Counts") +
        scale_color_manual(values=c("#000000","#FF0000")) +
        guides(linetype = guide_legend(override.aes= list(color = "#555555"))) 

dev.off()

```


## Models


```{r}
library(MASS)
library(DHARMa)
library(lme4)
library(lmerTest)
library(bbmle)
```

### Linear formula

```{r}
fit1 <- lm(Counts ~ Experiment + Olaparib*BRCA*Alc1, data = dataset)
print(summary(fit1))
cat("AIC: ", AIC(fit1))

simres <- simulateResiduals(fittedModel = fit1)
plot(simres)
```

```{r}
fit2 <- lm(NormCounts ~ Olaparib*BRCA*Alc1, data = dataset)
print(summary(fit2))
cat("AIC: ", AIC(fit2))

simres <- simulateResiduals(fittedModel = fit2)
plot(simres)
```

```{r}
fit3 <- lm(NormCounts2 ~ Olaparib*BRCA*Alc1, data = dataset)
print(summary(fit3))
cat("AIC: ", AIC(fit3))

simres <- simulateResiduals(fittedModel = fit3)
plot(simres)
```


```{r}
fit4 <- lmer(Counts ~ Olaparib*BRCA*Alc1 + (1|UID), data = dataset)
print(summary(fit4))
cat("AIC: ", AIC(fit4))

simres <- simulateResiduals(fittedModel = fit4)
plot(simres)
```



### Quadratic formula

```{r}
fit5 <- lm(Counts ~ Experiment + poly(Olaparib,2)*BRCA*Alc1, data = dataset)
print(summary(fit5))
cat("AIC: ", AIC(fit5))

simres <- simulateResiduals(fittedModel = fit5)
plot(simres)
```

```{r}
fit6 <- lm(NormCounts ~ poly(Olaparib,2)*BRCA*Alc1, data = dataset)
print(summary(fit6))
cat("AIC: ", AIC(fit6))

simres <- simulateResiduals(fittedModel = fit6)
plot(simres)
```

```{r}
fit7 <- lm(NormCounts2 ~ poly(Olaparib,2)*BRCA*Alc1, data = dataset)
print(summary(fit7))
cat("AIC: ", AIC(fit7))

simres <- simulateResiduals(fittedModel = fit7)
plot(simres)
```


```{r}
fit8 <- lmer(Counts ~ poly(Olaparib,2)*BRCA*Alc1 + (1|UID), data = dataset)
print(summary(fit8))
cat("AIC: ", AIC(fit8))

simres <- simulateResiduals(fittedModel = fit8)
plot(simres)
```

### Cubic formula

```{r}
fit9 <- lm(Counts ~ Experiment + poly(Olaparib,3)*BRCA*Alc1, data = dataset)
print(summary(fit9))
cat("AIC: ", AIC(fit9))

simres <- simulateResiduals(fittedModel = fit9)
plot(simres)
```

```{r}
fit10 <- lm(NormCounts ~ poly(Olaparib,3)*BRCA*Alc1, data = dataset)
print(summary(fit10))
cat("AIC: ", AIC(fit10))

simres <- simulateResiduals(fittedModel = fit10)
plot(simres)
```

```{r}
fit11 <- lm(NormCounts2 ~ poly(Olaparib,3)*BRCA*Alc1, data = dataset)
print(summary(fit11))
cat("AIC: ", AIC(fit11))

simres <- simulateResiduals(fittedModel = fit11)
plot(simres)
```


```{r}
fit12 <- lmer(Counts ~ poly(Olaparib,3)*BRCA*Alc1 + (1|UID), data = dataset)
print(summary(fit12))
cat("AIC: ", AIC(fit12))

simres <- simulateResiduals(fittedModel = fit12)
plot(simres)
```



# Compare Results


```{r}
ICtab(fit1,fit2,fit3,fit4,
      fit5,fit6,fit7,fit8,
      fit9,fit10,fit11,fit12,
      base=T)
```



# Final Result

```{r, fig.height=5, fig.width=18}
fit <- fit11

output <- coef(summary(fit))
output <- output[grep("Olaparib", rownames(output)),]

rownames(output) <- gsub("poly\\(|, [1-3]\\)","", rownames(output) )
rownames(output) <- gsub("Alc1",  paste0(" ",levels(dataset$Alc1)[1], " vs. "), rownames(output))
rownames(output)[!(grepl("vs", rownames(output)))] <- paste(rownames(output)[!(grepl("vs", rownames(output)))], levels(dataset$Alc1)[1],  sep = " in " )

rownames(output) <- gsub("BRCA",  paste0(" ",levels(dataset$BRCA)[1], " vs. "), rownames(output))
rownames(output)[!(grepl("vs.*vs|in", rownames(output)))] <- paste(rownames(output)[!(grepl("vs.*vs|in", rownames(output)))], levels(dataset$BRCA)[1],  sep = " in " )

rownames(output)[!(grepl("vs", rownames(output)))] <- paste(rownames(output)[!(grepl("vs", rownames(output)))], levels(dataset$BRCA)[1],  sep = " " )


# suggested result table
kable(output, row.names = T)

write.table(output, file = "Figure5H_Stats_Ref_h_d11.txt", quote = F, sep = "\t", row.names = T, col.names = NA)
```

```{r, fig.height=5, fig.width=18}
dataset$BRCA <- relevel(dataset$BRCA, ref = "d11/d11")

fit <- lm(NormCounts2 ~ poly(Olaparib,3)*BRCA*Alc1, data = dataset)

output <- coef(summary(fit))
output <- output[grep("Olaparib", rownames(output)),]

rownames(output) <- gsub("poly\\(|, [1-3]\\)","", rownames(output) )
rownames(output) <- gsub("Alc1",  paste0(" ",levels(dataset$Alc1)[1], " vs. "), rownames(output))
rownames(output)[!(grepl("vs", rownames(output)))] <- paste(rownames(output)[!(grepl("vs", rownames(output)))], levels(dataset$Alc1)[1],  sep = " in " )

rownames(output) <- gsub("BRCA",  paste0(" ",levels(dataset$BRCA)[1], " vs. "), rownames(output))
rownames(output)[!(grepl("vs.*vs|in", rownames(output)))] <- paste(rownames(output)[!(grepl("vs.*vs|in", rownames(output)))], levels(dataset$BRCA)[1],  sep = " in " )

rownames(output)[!(grepl("vs", rownames(output)))] <- paste(rownames(output)[!(grepl("vs", rownames(output)))], levels(dataset$BRCA)[1],  sep = " " )




# suggested result table
kable(output, row.names = T)

write.table(output, file = "Figure5H_Stats_Ref_d11_d11.txt", quote = F, sep = "\t", row.names = T, col.names = NA)
```


```{r, fig.height=5, fig.width=18}
# re-fit with GFP-ALC1 siBRCA1 reference
dataset$Alc1 <- relevel(dataset$Alc1, ref = "GFP-ALC1")
dataset$BRCA <- relevel(dataset$BRCA, ref = "d11/d11")
 

fit <- lm(NormCounts2 ~ poly(Olaparib,3)*BRCA*Alc1, data = dataset)

output <- coef(summary(fit))
output <- output[grep("Olaparib", rownames(output)),]

rownames(output) <- gsub("poly\\(|, [1-3]\\)","", rownames(output) )
rownames(output) <- gsub("Alc1",  paste0(" ",levels(dataset$Alc1)[1], " vs. "), rownames(output))
rownames(output)[!(grepl("vs", rownames(output)))] <- paste(rownames(output)[!(grepl("vs", rownames(output)))], levels(dataset$Alc1)[1],  sep = " in " )

rownames(output) <- gsub("BRCA",  paste0(" ",levels(dataset$BRCA)[1], " vs. "), rownames(output))
rownames(output)[!(grepl("vs.*vs|in", rownames(output)))] <- paste(rownames(output)[!(grepl("vs.*vs|in", rownames(output)))], levels(dataset$BRCA)[1],  sep = " in " )

rownames(output)[!(grepl("vs", rownames(output)))] <- paste(rownames(output)[!(grepl("vs", rownames(output)))], levels(dataset$BRCA)[1],  sep = " " )


# suggested result table
kable(output, row.names = T)

write.table(output, file = "Figure5H_Stats_Ref_GFP-ALC1_d11_d11.txt", quote = F, sep = "\t", row.names = T, col.names = NA)
```

# Anova

```{r}
fit11a <- lm(NormCounts2 ~ poly(Olaparib,3)*BRCA*Alc1, data = dataset)
fit11b <- lm(NormCounts2 ~ poly(Olaparib,3)*BRCA+Alc1, data = dataset)

# anova table
anova(fit11a, fit11b)
```


```{r}
fit11c <- lm(NormCounts2 ~ poly(Olaparib,3)*Alc1*BRCA, data = dataset)
fit11d <- lm(NormCounts2 ~ poly(Olaparib,3)*Alc1+BRCA, data = dataset)

# anova table
anova(fit11c, fit11d)
```



## New analysis

* fit model for groups (BRCA+Alc1)

```{r}
dataset$GSID <- factor(dataset$GSID, levels = unique(dataset$GSID))

GSID_levels <- levels(dataset$GSID)

for(g in seq_along(GSID_levels)){
        
        cat("Group: ", GSID_levels[g], "\n")
        
        dataset$GSID <- factor(dataset$GSID, levels = unique(dataset$GSID))
        dataset$GSID <- relevel(dataset$GSID, ref = GSID_levels[g])
        
        fit_group <- lm(NormCounts2 ~ poly(Olaparib,3)*GSID, data = dataset)
        
        print(summary(fit_group))
        cat("AIC: ", AIC(fit_group))
        
        
        simres <- simulateResiduals(fittedModel = fit_group)
        plot(simres)
        
        if(g == 1){
                output <- coef(summary(fit_group))
                output <- output[grep("Olaparib", rownames(output)),]
                rownames(output) <- gsub("poly\\(|, [1-3]\\)","", rownames(output))
                
                rownames(output) <- gsub("GSID",  paste0(" ",GSID_levels[g], " vs. "), rownames(output))
                rownames(output)[!(grepl("vs", rownames(output)))]  <- paste(rownames(output)[!(grepl("vs", rownames(output)))], levels(dataset$GSID)[1],  sep = " in " )

                
        } else {
                outtmp <- coef(summary(fit_group))
                outtmp <- outtmp[grep("Olaparib", rownames(outtmp)),]
                rownames(outtmp) <- gsub("poly\\(|, [1-3]\\)","", rownames(outtmp))
                
                rownames(outtmp) <- gsub("GSID",  paste0(" ",GSID_levels[g], " vs. "), rownames(outtmp))
                rownames(outtmp)[!(grepl("vs", rownames(outtmp)))]  <- paste(rownames(outtmp)[!(grepl("vs", rownames(outtmp)))], levels(dataset$GSID)[1],  sep = " in " )

                
                output <- rbind(output,outtmp)
        }
        
        if(g < length(GSID_levels)){
                
                output <- rbind(output, " ", colnames(output))
        }
        
}


# suggested result table
kable(output, row.names = T)

write.table(output, file = "Figure5H_Stats_New_All.txt", quote = F, sep = "\t", row.names = T, col.names = NA)
```

